BEGIN TRANSACTION;
CREATE TABLE R_EVE_REC (
    FK_ID_EVENTO INT NOT NULL,
    FK_ID_RECURSO INT NOT NULL,
    FOREIGN KEY (FK_ID_EVENTO)
        REFERENCES EVENTO (ID),
    FOREIGN KEY (FK_ID_RECURSO)
        REFERENCES RECURSO (ID)
);
CREATE TABLE R_EVE_BLOQ (
    FK_ID_EVENTO INT NOT NULL,
    FK_ID_BLOQUE INT NOT NULL,
    FOREIGN KEY (FK_ID_EVENTO)
        REFERENCES EVENTO (ID),
    FOREIGN KEY (FK_ID_BLOQUE)
        REFERENCES BLOQUE (ID)
);
CREATE TABLE RECURSO (
    ID INT PRIMARY KEY NOT NULL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT,
    TIPO_RECURSO TEXT
);
CREATE TABLE PERSONA (
    ID INT PRIMARY KEY NOT NULL,
    NOMBRE TEXT NOT NULL,
    TELEFONO TEXT,
    CORREO TEXT
);
CREATE TABLE EVENTO (
    ID INT PRIMARY KEY NOT NULL,
    NOMBRE TEXT NOT NULL,
    RESPONSABLE INT,
    BLOQUES INT,
    DESCRIPCION TEXT,
    RECURSO INT,
    FOREIGN KEY (RESPONSABLE)
        REFERENCES PERSONA (ID),
    FOREIGN KEY (BLOQUES)
        REFERENCES BLOQUE (ID),
    FOREIGN KEY (RECURSO)
        REFERENCES RECURSO (ID)
);
CREATE TABLE BLOQUE (
    ID INT PRIMARY KEY NOT NULL,
    TIMESTAMP_INICIO DATETIME NOT NULL,
    TIMESTAMP_TERMINO DATETIME NOT NULL
);
COMMIT;
